language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

before_script:
  - mysql -e 'create database larabook;'
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction --dev
  - chmod -R 777 app/storage/
  - php artisan serve &
  - sleep 5 # give artisan serve some time to start
  - php vendor/bin/codecept build

script:
  - php vendor/bin/codecept run unit
  - php vendor/bin/codecept run acceptance

after_failure:
  - cat app/storage/logs/laravel.log
  - cat tests/_output/*